#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════
   ANISMOKE — Build-time Config Generator
   Reads environment variables (from process.env or .env file)
   and writes js/config.js for the browser.
   
   Usage:
     node generate-config.js          # reads .env or process.env
   
   On Vercel/Netlify, set env vars in the dashboard — process.env
   is populated automatically, no .env file needed.
   ═══════════════════════════════════════════════════════════ */

const fs = require('fs');
const path = require('path');

// ── Load .env file if it exists (local dev) ──
function loadDotEnv() {
  const envPath = path.join(__dirname, '.env');
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    // Don't override existing process.env (CI/CD takes priority)
    if (!process.env[key]) {
      process.env[key] = val;
    }
  }
}

loadDotEnv();

// ── Collect config values ──
const config = {
  SUPABASE_URL:      process.env.SUPABASE_URL      || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY  || '',
  ANISMOKE_CONSUMET: process.env.ANISMOKE_CONSUMET  || '',
};

// ── Write js/config.js ──
const outPath = path.join(__dirname, 'js', 'config.js');
const content = `/* Auto-generated by generate-config.js — DO NOT EDIT */
window.ENV = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outPath, content, 'utf-8');
console.log(`[config] ✓ Written ${outPath}`);
console.log(`[config]   SUPABASE_URL:      ${config.SUPABASE_URL ? config.SUPABASE_URL.slice(0, 30) + '...' : '(empty)'}`);
console.log(`[config]   SUPABASE_ANON_KEY: ${config.SUPABASE_ANON_KEY ? '***' + config.SUPABASE_ANON_KEY.slice(-8) : '(empty)'}`);
console.log(`[config]   ANISMOKE_CONSUMET: ${config.ANISMOKE_CONSUMET || '(empty)'}`);
